// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
insert into posts (
  id,
  created_at,
  updated_at,
  title,
  url,
  description,
  published_at,
  feed_id
) 
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
) RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       sql.NullString
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsForUserFeed = `-- name: GetPostsForUserFeed :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id from posts
inner join feed_follows 
  on feed_follows.feed_id = posts.feed_id and feed_follows.user_id = $1
inner join feeds
  on feeds.id = posts.feed_id
order by feeds.name ASC, posts.published_at DESC, posts.id ASC 
limit $2
`

type GetPostsForUserFeedParams struct {
	UserID uuid.UUID
	Lim    int32
}

func (q *Queries) GetPostsForUserFeed(ctx context.Context, arg GetPostsForUserFeedParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserFeed, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserNewest = `-- name: GetPostsForUserNewest :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id from posts
inner join feed_follows 
  on feed_follows.feed_id = posts.feed_id and feed_follows.user_id = $1
order by posts.published_at DESC, posts.id ASC  
limit $2
`

type GetPostsForUserNewestParams struct {
	UserID uuid.UUID
	Lim    int32
}

func (q *Queries) GetPostsForUserNewest(ctx context.Context, arg GetPostsForUserNewestParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserNewest, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserOldest = `-- name: GetPostsForUserOldest :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id from posts
inner join feed_follows 
  on feed_follows.feed_id = posts.feed_id and feed_follows.user_id = $1
order by posts.published_at ASC, posts.id ASC
limit $2
`

type GetPostsForUserOldestParams struct {
	UserID uuid.UUID
	Lim    int32
}

func (q *Queries) GetPostsForUserOldest(ctx context.Context, arg GetPostsForUserOldestParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserOldest, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserTitle = `-- name: GetPostsForUserTitle :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id from posts
inner join feed_follows 
  on feed_follows.feed_id = posts.feed_id and feed_follows.user_id = $1
order by title ASC, posts.id ASC  
limit $2
`

type GetPostsForUserTitleParams struct {
	UserID uuid.UUID
	Lim    int32
}

func (q *Queries) GetPostsForUserTitle(ctx context.Context, arg GetPostsForUserTitleParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserTitle, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
